[package]
name = "vaccine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
difflib = "0.4.0"
structopt = "0.3.26"
tl = "0.7.8"
ureq = "2.9.4"
